## Import NumPy in Jupyter notebook.

In [73]:
import numpy as np

## Generate a 1D NumPy array of 10 random integers between 1 and 100.

In [74]:
a=np.random.randint(1,100,10)
a

array([64,  2, 21, 76, 88, 89, 52, 97, 10, 95])

## Access and print the first and last elements of the array.

In [75]:
print(a[0])
print(a[-1])

64
95


## Generate a 2D NumPy array of shape (3, 3) with random floating-point numbers.

In [87]:
b=np.random.rand(3, 3)
b

array([[0.96464888, 0.33609746, 0.42193042],
       [0.18824291, 0.34059336, 0.79063763],
       [0.59028526, 0.84747982, 0.72238071]])

## Use the 2D array generated in Exercise 1 c. Practice slicing arrays to access sub-arrays.
## Print the first row of the 2D array.


In [88]:
print(b[0,:])

[0.96464888 0.33609746 0.42193042]


## Print the last column of the 2D array.

In [89]:
print(b[:,-1])

[0.42193042 0.79063763 0.72238071]


## Create and print a sub-array consisting of the first two rows and first two columns.

In [90]:
c=b[:2,:2]
print(c)

[[0.96464888 0.33609746]
 [0.18824291 0.34059336]]


## Generate two 1D NumPy arrays of 5 random integers each. 

In [91]:
a1=np.random.randint(1,50,5)
a2=np.random.randint(1,50,5)
print("firtst array: ",a1)
print("second array: ",a2)

firtst array:  [40 16 21 27 27]
second array:  [31  3 43  3 11]


## Add the two arrays and print the result.

In [92]:
ad=a1+a2
print("sum of 2 arrays: ",ad)

sum of 2 arrays:  [71 19 64 30 38]


## Multiply the two arrays (element-wise) and print the result.

In [93]:
mul=a1*a2
print("product of 2 arrays: ",mul)

product of 2 arrays:  [1240   48  903   81  297]


## Calculate the square of every element in the first array and print it.

In [94]:
squ=a1**2
print("a1 array: ",a1)
print("square of every element in array a1: ",squ)

a1 array:  [40 16 21 27 27]
square of every element in array a1:  [1600  256  441  729  729]


## Generate two 2D NumPy arrays, A of shape (2, 3) and B of shape (3, 2), with random integers.

In [95]:
A=np.random.randint(1,50,(2, 3))
B=np.random.randint(1,50,(3, 2))
print(A)
print()
print(B)

[[ 8 39 48]
 [25 47 24]]

[[43  9]
 [36 33]
 [33 33]]


## Perform matrix multiplication between A and B (using np.dot() or the @ operator) and print the result.

In [96]:
matmul=A@B
matmul1=np.dot(A,B)
print("multiplication using @")
print(matmul)
print("multiplication using np.dot()")
print(matmul1)

multiplication using @
[[3332 2943]
 [3559 2568]]
multiplication using np.dot()
[[3332 2943]
 [3559 2568]]


## Can A and B perform element-wise multiplication using *, why?

In [97]:
mat=A*B
print(mat)

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

* Matrix A and B can not be multiplied element wise using the * operator as they both have different shapes.